export const DEFAULT_SETTINGS = {
    shop_name: 'Lyang Nghĩa',
    shop_address: '',
    shop_phone: '',
    shop_bank: '',
    shop_bank_account: '',
    shop_bank_user: '',
    invoice_font_size: '13',
    invoice_font_family: 'Inter, sans-serif',
    invoice_footer: 'Cảm ơn Quý Khách!',
    invoice_show_thank_you: 'true',
    invoice_thank_you_message: 'Cảm ơn Quý Khách & Hẹn Gặp Lại!',
    paper_size: 'A4',
    invoice_header_color: '#2D5A27',
    invoice_show_logo: 'true',
    invoice_logo_url: '',
    invoice_table_font_size: '12',
    invoice_row_padding: '4',
    invoice_item_spacing: '2',
    invoice_show_header: 'true',
    invoice_show_footer: 'true',
    invoice_show_signatures: 'true',
    invoice_col_stt: '40',
    invoice_col_name: '250',
    invoice_col_unit: '60',
    invoice_col_box: '70',
    invoice_col_qty: '70',
    invoice_col_price: '100',
    invoice_col_total: '120',
    invoice_show_col_stt: 'true',
    invoice_show_col_name: 'true',
    invoice_show_col_unit: 'true',
    invoice_show_col_box: 'true',
    invoice_show_col_qty: 'true',
    invoice_show_col_price: 'true',
    invoice_show_col_total: 'true',
    invoice_show_col_unit_secondary: 'true',
    invoice_col_unit_secondary: '80',
    invoice_store_name_size: '24',
    invoice_store_info_size: '11',
    invoice_customer_info_size: '12',
    invoice_footer_label_size: '14',
    invoice_footer_value_size: '14',
    invoice_table_header_size: '11',
    invoice_table_content_size: '12',
    invoice_table_width: '100',
    invoice_table_border_color: '#000000',
    invoice_table_border_width: '1',
    invoice_table_header_bg: '#f8fafc',
    invoice_table_header_color: '#000000',
    invoice_header_spacing: '20',
    invoice_footer_spacing: '20',
    invoice_header_font_size: '24',
    invoice_footer_line_spacing: '4',
    invoice_footer_show_lines: 'true',
    invoice_customer_info_spacing: '4',
    invoice_custom_font_name: '',
    invoice_show_underline: 'false',
    invoice_margin_top: '10',
    invoice_margin_bottom: '10',
    invoice_margin_left: '10',
    invoice_margin_right: '10',
    invoice_table_margin_bottom: '10',
    invoice_line_spacing: '1.4',
    invoice_orientation: 'portrait',
    invoice_title_size: '22',
    invoice_total_section_size: '14',
    invoice_total_section_margin_top: '5',
    invoice_total_line_margin_top: '2',
    invoice_total_line_margin_bottom: '10',
    invoice_total_balance_size: '18',
    invoice_show_shop_name: 'true',
    invoice_show_address: 'true',
    invoice_show_phone: 'true',
    invoice_show_id: 'true',
    invoice_show_date: 'true',
    invoice_show_customer_info: 'true',
    invoice_show_table: 'true',
    invoice_show_summary: 'true',
    invoice_show_total_items: 'true',
    invoice_show_total_qty: 'true',
    invoice_show_old_debt: 'true',
    invoice_show_paid: 'true',
    invoice_show_balance: 'true',
    invoice_column_spacing: '10',
    // UI Settings
    ui_show_doraemon: 'true',
    // Invoice Table Styling
    invoice_table_border: 'true',
    invoice_table_border_rows: 'true',
    invoice_table_border_cols: 'true',
    invoice_table_border_thickness: 'thin',
    invoice_table_border_style: 'solid',
    invoice_table_header_bg_enabled: 'true',
    invoice_table_zebra_stripe: 'false',
    invoice_table_font_size_preset: 'normal',
    // Invoice Footer Toggles
    invoice_show_total_amount: 'true',
    invoice_show_notes: 'true',
    invoice_show_secondary_qty: 'false',
    invoice_show_total_secondary_qty: 'false',
    invoice_show_bank_info: 'true',
    invoice_col_secondary_qty_width: '80',
    invoice_total_summary_font_size: '11',
    // Keyboard Shortcuts
    kb_search: 'F2',
    kb_pay: 'F9',
    kb_save: 'F12',
    kb_new: 'F4',
    kb_hold: 'F8',
    pos_input_mode: 'Retail',
    report_title: 'BÁO CÁO CHI TIẾT GIAO DỊCH',
    report_note: '',
    report_watermark: '',
    col_id_label: 'Mã đơn',
    col_date_label: 'Ngày',
    col_pttt_label: 'PTTT',
    col_amount_label: 'Thành tiền',
    invoice_title_badge: 'false',
    invoice_title_badge_bg: '#2d5016',
    invoice_title_badge_border: '#86efac',
    invoice_title_badge_text_color: '#ffffff',
    invoice_table_header_border: 'false',
    invoice_table_header_border_width: '1',
    invoice_table_header_border_color: '#000000',
    invoice_table_header_is_badge: 'false',
    invoice_table_header_badge_bg: '#2d5016',
    invoice_table_header_badge_border: '#86efac',
    invoice_table_header_badge_text_color: '#ffffff',
    ui_show_rainbow_border: 'true',
};

export const resolveSettings = (s, type) => {
    const settings = { ...DEFAULT_SETTINGS, ...s };
    const rs = {};

    Object.keys(DEFAULT_SETTINGS).forEach(key => {
        const typeKey = `${type}_${key}`;
        if (settings[typeKey] !== undefined && settings[typeKey] !== null && settings[typeKey] !== '') {
            rs[key] = settings[typeKey];
        } else {
            rs[key] = settings[key] !== undefined ? settings[key] : DEFAULT_SETTINGS[key];
        }
    });

    return rs;
};
